[package]
name = "maxima-lib"
version = "1.0.0"
edition = "2021"
authors = ["Sean Kahler <sean@battleda.sh>"]
categories = ["games"]
description = "A free and open-source replacement for the EA Desktop Launcher"
keywords = ["electronic-arts", "linux-gaming"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/ArmchairDevelopers/Maxima"
documentation = "https://docs.rs/maxima"
rust-version = "1.81.0"

[dependencies]
tokio = { version = "1.52.3", features = [
    "full",
    "rt",
    "rt-multi-thread",
    "time",
    "net",
] }
moka = { version = "0.12.15", features = ["sync"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
quick-xml = { version = "0.30.0", features = ["serialize"] }
paste = "1.0.15"
hex = "0.4.3"
lazy_static = "1.5.0"
reqwest = { version = "0.11.27", features = ["stream", "rustls-tls", "gzip", "json"], default-features = false }
base64 = "0.21.7"
base62 = "2.2.4"
log = "0.4.29"
enable-ansi-support = "0.2.1"
chrono = "0.4.44"
regex = "1.12.3"
directories = "5.0.1"
open = "5.3.5"
querystring = "1.1.0"
ureq = { version = "2.12.1", features = ["tls"] }
sysinfo = "0.29.11"
strum_macros = "0.25.3"
sha2-const = "0.1.2"
tar = "0.4"
flate2 = { version = "=1.0.28", default-features = false, features = ["zlib-default"] }
xz2 = "0.1.7"
zstd = "0.13.3"
toml = "0.8.23"
bytebuffer = "2.3.0"
derive-getters = "0.3.0"
derive_builder = "0.12.0"
mac_address = "1.1.8"
filetime = "0.2.29"
rand = "0.9.4"
ring = "0.17.14"
futures = "0.3.32"
prost = "0.12.6"
encoding = "0.2.33"
async-compression = { version = "0.4.5", features = ["tokio", "deflate"] }
tokio-util = { version = "0.7.18", features = ["io", "compat"] }
uuid = "1.20.0"
tokio-rustls = "0.23.4"
rustls = "0.20.9"
webpki-roots = "0.22.6"
aes = "0.8.4"
ecb = { version = "0.1.2", features = ["std"] }
cbc = { version = "0.1.2", features = ["std"] }
glob = "0.3.3"
md5 = "0.7.0"
bytes = "1.11.1"
async-trait = "0.1.89"
crc32fast = "1.5.0"
async-recursion = "1.1.1"
pelite = "0.10.0"
gethostname = "0.5.0"
thiserror = "2.0.18"
url = "2.5.8"
http = "0.2.12"
globset = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
    "memoryapi",
    "handleapi",
    "synchapi",
    "wincon",
    "consoleapi",
    "psapi",
    "wininet",
    "winerror",
    "iphlpapi",
    "tcpmib",
    "winsvc",
    "impl-default"
] }
winreg = "0.51.0"
windows-service = "0.6.0"
is_elevated = "0.1.2"
widestring = "1.2.1"
wmi = "0.13.4"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8"
io-kit-sys = "0.5.0"
which = "8.0.2"

[build-dependencies]
prost-build = "0.12.6"

[lib]
name = "maxima"
path = "src/lib.rs"
