[package]
name = "maxima-service"
version = "0.1.0"
authors = ["Sean Kahler <sean@battleda.sh>"]
edition = "2021"

[dependencies]
maxima-lib = { path = "../maxima-lib" }
tokio = { version = "1.52.3", features = [ "full", "rt", "rt-multi-thread", "time", "net" ] }
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.150"
paste = "1.0.15"
reqwest = { version = "0.13.4", features = ["stream", "rustls"], default-features = false }
base64 = "0.22.1"
log = "0.4.30"
regex = "1.12.3"
directories = "6.0.0"
structured-logger = "1.0.5"
actix-web = "4.13.0"
sha2 = "0.11.0"
derive_more = "2.1.1"
hex = "0.4.3"
thiserror = "2.0.18"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [ "memoryapi", "handleapi", "synchapi", "wincon", "consoleapi" ] }
winreg = "0.56.0"
windows-service = "0.8.1"

[build-dependencies]
maxima-resources = { path = "../maxima-resources" }

[[bin]]
name = "maxima-service"
path = "src/main.rs"
