[package]
name = "maxima-bootstrap"
description = "Maxima handler for custom EA protocols"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
maxima-lib = { path = "../maxima-lib" }
tokio = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["query"] }
base64 = { workspace = true }
url = { workspace = true }
urlencoding = "2.1.3"
thiserror = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
cacao = "0.3.2"

[build-dependencies]
maxima-resources = { path = "../maxima-resources" }

[[bin]]
name = "maxima-bootstrap"
path = "src/main.rs"

[package.metadata.bundle]
name = "MaximaBootstrap"
identifier = "io.github.ArmchairDevelopers.MaximaBootstrap"
osx_url_schemes = ["qrc", "link2ea", "origin2"]
