query GetSubscriptionStatus($overrideCountryCode: String!) {
  me {
    id: pd
    nonRecurringSubscriptionsSummary {
      start
      end
      __typename
    }
    subscriptions {
      ...subscriptionService
      __typename
    }
    steamSubscriptions: subscriptions(storefronts: [STEAM], status: ACTIVE) {
      ...subscriptionService
      __typename
    }
    __typename
  }
}

fragment subscriptionService on ServiceSubscription {
  start
  end
  level
  recurring
  externalLoginRequired
  status
  acquisitionMethod
  offer(overrideCountryCode: $overrideCountryCode) {
    offerId
    offerName
    duration
    ...purchaseOptionSubscription
    ...lowestPricePurchaseOptionSubscription
    __typename
  }
  offerId
  platform
  __typename
}

fragment purchaseOptionSubscription on SubscriptionOffer {
  purchaseOptions {
    currency
    discountPercentage
    displayOriginalTotal
    displayTotalWithDiscount
    ...purchaseOptionDiscountsSubscription
    __typename
  }
  __typename
}

fragment purchaseOptionDiscountsSubscription on SubscriptionPurchaseOption {
  discounts {
    discountType
    displayAmount
    percentage
    endDate
    startDate
    __typename
  }
  __typename
}

fragment lowestPricePurchaseOptionSubscription on SubscriptionOffer {
  lowestPricePurchaseOption {
    displayMonthlyEquivalentWithDiscount
    displayOriginalTotal
    displayTotalWithDiscount
    discountPercentage
    currency
    ...purchaseOptionDiscountsSubscription
    __typename
  }
  __typename
}
