[package]
name = "maxima-tui"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
maxima-lib = { path = "../maxima-lib" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
inquire = { workspace = true }
ratatui = "0.30.2"
strum = { workspace = true }
color-eyre = "0.6.5"
tokio-stream = "0.1.19"

[target.'cfg(windows)'.dependencies]
is_elevated = { workspace = true }

[build-dependencies]
maxima-resources = { path = "../maxima-resources" }

[[bin]]
name = "maxima-tui"
path = "src/main.rs"
