[package]
name = "maxima-cli"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
maxima-lib = { path = "../maxima-lib" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
inquire = { workspace = true }
rustls = { workspace = true }

[target.'cfg(windows)'.dependencies]
is_elevated = { workspace = true }

[build-dependencies]
maxima-resources = { path = "../maxima-resources" }

[[bin]]
name = "maxima-cli"
path = "src/main.rs"
