query GetPlayerByPdLite($pd: ID!, $isMutualFriendsEnabled: Boolean = false) {
  playerByPd(pd: $pd) {
    ...PlayerWithMutualFriendsCount
    friends(paging: {offset: 0, limit: 1}) {
      totalCount
      __typename
    }
    ownedGameProducts(paging: {limit: 1}, productFound: true, type: [DIGITAL_FULL_GAME]) {
      totalCount
      __typename
    }
    __typename
  }
}

fragment PlayerWithMutualFriendsCount on Player {
  ...Player
  mutualFriends @include(if: $isMutualFriendsEnabled) {
    totalCount
    __typename
  }
  __typename
}

fragment Player on Player {
  id: pd
  pd
  psd
  displayName
  uniqueName
  nickname
  avatar {
    ...Avatar
    __typename
  }
  relationship
  __typename
}

fragment Avatar on AvatarList {
  large {
    ...image
    __typename
  }
  medium {
    ...image
    __typename
  }
  small {
    ...image
    __typename
  }
  __typename
}

fragment image on Image {
  height
  width
  path
  __typename
}
